import type { Referencia } from '@/content/types'

export const referencias: Referencia[] = [
  {
    id: 'fase1',
    autores: 'Absci Corporation',
    titulo:
      'Absci Announces Positive Interim Phase 1 Data from the HEADLINE™ Trial of ABS-201, a Novel Antibody Targeting the Prolactin Receptor (PRLR)',
    veiculo: 'Comunicado ao investidor',
    data: '24 jun. 2026',
    url: 'https://investors.absci.com/news-releases/news-release-details/absci-announces-positive-interim-phase-1-data-headlinetm-trial/',
    tipo: 'primaria',
  },
  {
    id: 'primeiros-dosados',
    autores: 'Absci Corporation',
    titulo:
      'Absci Announces First Participants Dosed in Phase 1/2a HEADLINE™ Trial of AI-Designed Antibody ABS-201™ for Androgenetic Alopecia',
    veiculo: 'Comunicado ao investidor',
    data: '4 dez. 2025',
    url: 'https://investors.absci.com/news-releases/news-release-details/absci-announces-first-participants-dosed-phase-12a-headlinetm/',
    tipo: 'primaria',
  },
  {
    id: 'exvivo',
    autores: 'Absci Corporation',
    titulo:
      'Absci Reports New Human Ex Vivo Data Demonstrating That ABS-201™ Stimulates Hair Growth and Regenerates Stem Cell Niche to Potentially Reverse Follicle Miniaturization',
    veiculo: 'Comunicado ao investidor',
    data: '11 dez. 2025',
    url: 'https://investors.absci.com/news-releases/news-release-details/absci-reports-new-human-ex-vivo-data-demonstrating-abs-201tm',
    tipo: 'primaria',
  },
  {
    id: 'oferta',
    autores: 'Absci Corporation',
    titulo:
      'Absci Announces Pricing of $100 Million Underwritten Offering with Leading Strategic and Financial Investors',
    veiculo: 'Comunicado ao investidor',
    data: '24 jun. 2026',
    url: 'https://investors.absci.com/news-releases/news-release-details/absci-announces-pricing-100-million-underwritten-offering',
    tipo: 'primaria',
  },
  {
    id: 'q2-2026',
    autores: 'Absci Corporation',
    titulo: 'Absci Reports Business Updates and Second Quarter 2026 Financial and Operating Results',
    veiculo: 'Comunicado ao investidor',
    data: '11 ago. 2026',
    url: 'https://investors.absci.com/news-releases/news-release-details/absci-reports-business-updates-and-second-quarter-2026-financial',
    tipo: 'primaria',
  },
  {
    id: 'caso-absci',
    autores: 'Absci Corporation',
    titulo: 'ABS-201™ for Androgenetic Alopecia — case study',
    veiculo: 'absci.com',
    data: 'acesso em 22 set. 2026',
    url: 'https://www.absci.com/abs-201-case-study/',
    tipo: 'primaria',
  },
  {
    id: 'headline-registro',
    autores: 'Absci Corporation',
    titulo:
      'A Study of ABS-201 in Healthy Participants and Participants With Androgenetic Alopecia (HEADLINE) — NCT07317544',
    veiculo: 'ClinicalTrials.gov',
    data: 'acesso em 22 set. 2026',
    url: 'https://clinicaltrials.gov/study/NCT07317544',
    tipo: 'registro',
  },
  {
    id: 'stat-lilly',
    autores: 'STAT News',
    titulo: 'Eli Lilly dives into hair loss treatments with investment in AI startup Absci',
    veiculo: 'statnews.com',
    data: '24 jun. 2026',
    url: 'https://www.statnews.com/2026/06/24/eli-lilly-absci-hair-loss-treatments/',
    tipo: 'secundaria',
  },
  {
    id: 'ddw',
    autores: 'Drug Discovery World',
    titulo: 'Absci reports positive data from Phase I alopecia trial',
    veiculo: 'ddw-online.com',
    data: 'jun. 2026',
    url: 'https://www.ddw-online.com/absci-reports-positive-data-from-phase-i-alopecia-trial-42552-202606/',
    tipo: 'secundaria',
  },
  {
    id: 'practical-derm',
    autores: 'Practical Dermatology',
    titulo: 'Prolactin Receptor Blockade May Promote Hair Growth via Follicular Stem Cell Activation',
    veiculo: 'practicaldermatology.com',
    data: '2026',
    url: 'https://practicaldermatology.com/news/prolactin-receptor-blockade-may-promote-hair-growth-via-follicular-stem-cell-activation/2485612/',
    tipo: 'secundaria',
  },
  {
    id: 'hopemed',
    autores: 'Hope Medicine Inc.',
    titulo:
      'Hope Medicine Announces US FDA Clearance for Phase II Clinical Trial of a First-in-class Monoclonal Antibody, HMI-115, in Androgenetic Alopecia',
    veiculo: 'PR Newswire',
    data: '2022',
    url: 'https://www.prnewswire.com/news-releases/hope-medicine-announces-us-fda-clearance-for-phase-ii-clinical-trial-of-a-first-in-class-monoclonal-antibody-hmi-115-in-androgen-alopecia-301467402.html',
    tipo: 'primaria',
  },
  {
    id: 'hmi115-registro',
    autores: 'Hope Medicine Inc.',
    titulo: 'A Study of HMI-115 in Subjects With Androgenetic Alopecia — NCT06118866',
    veiculo: 'ClinicalTrials.gov',
    data: 'acesso em 22 set. 2026',
    url: 'https://clinicaltrials.gov/study/NCT06118866',
    tipo: 'registro',
  },
  {
    id: 'hmi115-fase1b',
    autores: 'Hope Medicine Inc.',
    titulo: 'Positive Outcome from a Phase Ib Study in Australia Treating Patients with Androgenic Alopecia',
    veiculo: 'PR Newswire',
    data: 'jan. 2024',
    url: 'https://www.prnewswire.com/news-releases/positive-outcome-from-a-phase-ib-study-in-australia-treating-patients-with-androgenic-alopecia-302031051.html',
    tipo: 'primaria',
  },
  {
    id: 'absci-teleconferencia-q2',
    autores: 'Absci Corporation',
    titulo: 'Absci (ABSI) Q2 2026 Earnings Call Transcript',
    veiculo: 'Transcrição da teleconferência de resultados, via The Motley Fool',
    data: '11 ago. 2026',
    url: 'https://www.fool.com/earnings/call-transcripts/2026/08/19/absci-absi-q2-2026-earnings-call-transcript/',
    tipo: 'primaria',
  },
  {
    id: 'patente-bayer',
    autores: 'Bayer AG',
    titulo: 'Prolactin receptor antibody for male and female pattern hair loss — WO2019011719A1',
    veiculo: 'Pedido de patente internacional (PCT)',
    data: '2019',
    url: 'https://patents.google.com/patent/WO2019011719A1/en',
    tipo: 'primaria',
  },
  {
    id: 'lancet-endometriose',
    autores: 'Investigadores do ensaio NCT05101317',
    titulo:
      'Safety and efficacy of subcutaneous injection with HMI-115 versus placebo in endometriosis-associated pain in premenopausal women: a multicentre, double-blind, randomised, proof-of-concept phase 2 trial',
    veiculo: "The Lancet Obstetrics, Gynaecology, & Women's Health",
    data: 'nov. 2025',
    url: 'https://www.thelancet.com/journals/lanogw/article/PIIS3050-5038(25)00032-9/abstract',
    tipo: 'literatura',
  },
  {
    id: 'goffin-nb2',
    autores: 'Goffin V. et al.',
    titulo:
      'Antagonistic Properties of Human Prolactin Analogs That Show Paradoxical Agonistic Activity in the Nb2 Bioassay',
    veiculo: 'Journal of Biological Chemistry',
    data: '1996',
    url: 'https://www.sciencedirect.com/science/article/pii/S0021925818319136',
    tipo: 'literatura',
  },
  {
    id: 'revisao-anticorpos',
    autores: 'Kim H. et al.',
    titulo: 'Recent approaches of antibody therapeutics in androgenetic alopecia',
    veiculo: 'PMC (National Library of Medicine)',
    data: '2024',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11362041/',
    tipo: 'literatura',
  },
]

export default referencias
